name: Publish to npm

on:
  push:
    branches: [main] # Trigger workflow on push to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Setup Node.js and npm
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x' # Use your preferred Node.js version
          registry-url: 'https://registry.npmjs.org'

      # Step 3: Authenticate with npm
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      # Step 4: Install dependencies
      - run: npm install

      # Step 5: Build the package (if applicable)
      - run: npm run build

      # Step 6: Publish the package to npm
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
